services:
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=REMSFAL
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - remsfal

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - remsfal
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  zeebe:
    image: camunda/zeebe:latest
    container_name: camunda
    environment:
      - ZEEBE_BROKER_CLUSTER_SIZE=1
      - ZEEBE_BROKER_PARTITIONS_COUNT=1
      - ZEEBE_BROKER_REPLICATION_FACTOR=1
    ports:
      - "26500:26500"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
      
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"  # CQL native transport port
      - "7000:7000"  # Intra-node communication (optional)
      - "7001:7001"  # TLS intra-node communication (optional)
      - "7199:7199"  # JMX monitoring (optional)
    environment:
      - CASSANDRA_CLUSTER_NAME=REMSFAL-CASSANDRA-CLUSTER
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  remsfal:
    driver: bridge