version: '3.8'
services:
  mysql:
    image: mysql:lts
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=REMSFAL

  grafana:
    networks:
      - remsfal
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - remsfal
    ports:
      - '9090:9090'

  zeebe:
    image: camunda/zeebe:latest
    ports:
      - "26500:26500" # gRPC-Port für Client-Verbindungen
    environment:
      - ZEEBE_BROKER_CLUSTER_SIZE=1
      - ZEEBE_BROKER_PARTITIONS_COUNT=1
      - ZEEBE_BROKER_REPLICATION_FACTOR=1

networks:
  remsfal:
    driver: bridge