services:
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=REMSFAL
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - remsfal

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    networks:
      - remsfal
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  zeebe:
    image: camunda/zeebe:latest
    container_name: camunda
    environment:
      - ZEEBE_BROKER_CLUSTER_SIZE=1
      - ZEEBE_BROKER_PARTITIONS_COUNT=1
      - ZEEBE_BROKER_REPLICATION_FACTOR=1
    ports:
      - "26500:26500"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
      
  cassandra-seed:
    image: cassandra:latest
    container_name: cassandra-seed
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    ports:
      - "9042:9042"
      - "7000:7000"

  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-seed
    ports:
      - "9043:9042" # Alternative port mapping for node1
      - "7001:7000"


networks:
  remsfal:
    driver: bridge