version: '3.8'
services:
  mysql:
    image: mysql:lts
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=REMSFAL

  grafana:
    networks:
      - remsfal
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - remsfal
    ports:
      - '9090:9090'

  zeebe:
    image: camunda/zeebe:latest
    ports:
      - "26500:26500"
    environment:
      - ZEEBE_BROKER_CLUSTER_SIZE=1
      - ZEEBE_BROKER_PARTITIONS_COUNT=1
      - ZEEBE_BROKER_REPLICATION_FACTOR=1

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
      

networks:
  remsfal:
    driver: bridge