package de.remsfal.core.json.project;

import jakarta.annotation.Nullable;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Size;

import java.util.Set;
import java.util.UUID;

import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.immutables.value.Value.Immutable;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import de.remsfal.core.ImmutableStyle;
import de.remsfal.core.json.AddressJson;
import de.remsfal.core.model.project.ProjectMemberModel;
import de.remsfal.core.model.project.ProjectModel;
import de.remsfal.core.validation.PostValidation;

/**
 * @author Alexander Stanik [alexander.stanik@htw-berlin.de]
 */
@Immutable
@ImmutableStyle
@Schema(description = "A project")
@JsonDeserialize(as = ImmutableProjectJson.class)
@JsonNaming(PropertyNamingStrategies.LowerCamelCaseStrategy.class)
public abstract class ProjectJson implements ProjectModel {

    @Null
    @Nullable
    @Schema(readOnly = true, description = "Unique identifier of the project (generated by server)")
    @Override
    public abstract UUID getId();

    @NotNull
    @NotBlank
    @Size(min = 1, max = 99, message = "The title must be between 1 and 255 characters")
    @Override
    public abstract String getTitle();

    @Nullable
    @Null(groups = PostValidation.class)
    @Size(max = 255, message = "The owner cannot be longer than 255 characters")
    @Override
    public abstract String getOwner();

    @Nullable
    @Null(groups = PostValidation.class)
    @Size(max = 255, message = "The care of cannot be longer than 255 characters")
    @Override
    public abstract String getCareOf();

    @Valid
    @Nullable
    @Null(groups = PostValidation.class)
    @Override
    public abstract AddressJson getAddress();

    @Null
    @Nullable
    @Schema(readOnly = true, description = "Project members (managed separately via members endpoint)")
    @Override
    public abstract Set<ProjectMemberJson> getMembers();

    public static ProjectJson valueOf(final ProjectModel model) {
        final ImmutableProjectJson.Builder builder = ImmutableProjectJson.builder()
            .id(model.getId())
            .title(model.getTitle())
            .owner(model.getOwner())
            .careOf(model.getCareOf())
            .address(AddressJson.valueOf(model.getAddress()));
        for (ProjectMemberModel member : model.getMembers()) {
            builder.addMembers(ProjectMemberJson.valueOf(member));
        }
        return builder.build();
    }

}
