name: Build REMSFAL Frontend
description: Setting up Node and building REMSFAL Frontend

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: remsfal-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: remsfal-${{ env.cache-name }}
    - name: Install dependencies
      run: npm ci
    - name: Generate Client
      run: |
        echo "TODO: run NPM"
